name: PocketMine-MP

on:
  workflow_dispatch:

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: hostibu
          password: ${{ secrets.SECRET_PASSWORD }}

      - name: DEBUG — Print GitHub Context
        run: |
          echo "Actor: ${{ github.actor }}"
          echo "Repository: ${{ github.repository }}"
          echo "Repository Owner: ${{ github.repository_owner }}"

      - name: DEBUG — Check current Docker context
        run: docker context ls

      - name: DEBUG — List docker images before build
        run: docker images

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: ./game/Minecraft/PocketMine-MP
          file: ./game/Minecraft/PocketMine-MP/Dockerfile
          push: true
          tags: ghcr.io/hostibu/yolks:pocketmine-mp

      - name: DEBUG — List docker images after push
        run: docker images

      - name: DEBUG — Curl API to check package visibility
        run: |
          curl -s -H "Authorization: Bearer ${{ secrets.SECRET_PASSWORD }}" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/orgs/hostibu/packages?package_type=container
