name: Game
on:
  push:
    branches:
      - main
    paths:
      - game/**/Dockerfile
jobs:
  build-and-push:
    name: "game:${{ matrix.path }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        path: ${{ fromJSON(steps.get_paths.outputs.paths) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Get Dockerfile paths
        id: get_paths
        run: |
          paths=$(find game -name Dockerfile -print | sed 's|/Dockerfile||')
          echo "paths=$(echo $paths | jq -R -s -c 'split(\" \")')" >> $GITHUB_OUTPUT
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.SECRET_PASSWORD }}
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: ./${{ matrix.path }}
          file: ./${{ matrix.path }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/game:${{ matrix.path }}
