name: Game
on:
  push:
    branches:
      - main
    paths:
      - game/**/Dockerfile
  workflow_dispatch:  # Manuel başlatma için gerekli etkinlik

jobs:
  get-paths:
    name: Get Dockerfile paths
    runs-on: ubuntu-latest
    outputs:
      paths: ${{ steps.get_paths.outputs.paths }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Get Dockerfile paths
        id: get_paths
        run: |
          set -x  # Komutları adım adım yazdırmaya başla
          # Dockerfile'ları bul ve yol karakterlerini düzgün işle
          paths=$(find game -name Dockerfile -print0 | xargs -0 -n 1 dirname)
          echo "Found paths: $paths"
          # Yolları JSON formatına dönüştür, çift tırnakları düzgün kaçır
          echo "paths=$(echo $paths | jq -R -s -c 'split(\" \")')" >> $GITHUB_OUTPUT
          
  build-and-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    needs: get-paths
    strategy:
      fail-fast: false
      matrix:
        path: ${{ fromJson(needs.get-paths.outputs.paths) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.SECRET_PASSWORD }}
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: ./${{ matrix.path }}
          file: ./${{ matrix.path }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/game:${{ matrix.path }}
