name: PocketMine-MP
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.SECRET_PASSWORD }}
      - uses: docker/build-push-action@v4
        with:
          context: ./game/Minecraft/PocketMine-MP
          file: ./game/Minecraft/PocketMine-MP/Dockerfile
          tags: |
            ghcr.io/${{ github.repository_owner }}/game:pocketmine-mp